### ISSUE TITLE
Cannot find module '@kontent-ai/rich-text-resolver' or its corresponding type declarations in v1.0.0

### ISSUE THREAD

**Issue by cwaespi** [kontent-ai/rich-text-resolver-js#43]
### Brief bug description

After update from @kontent-ai/rich-text-resolver 0.0.5 to 1.0.0 an error occured:
`Cannot find module '@kontent-ai/rich-text-resolver' or its corresponding type declarations`

### Repro steps

1. Update @kontent-ai/rich-text-resolver to 1.0.0
2. Try to import anything from the library

### Expected behavior

Cannot use the library in version 1.0.0 as it doesn't export any functionality.

### Test environment

- node v20.11.0
- typescript 5.3.3

### Screenshots

![image](https://github.com/kontent-ai/rich-text-resolver-js/assets/14320406/3b547691-fc83-46ff-afc6-b84f8bc091c4)

**Comment by pokornyd** [comment]
hello there, thank you for the issue submission. I was able to reproduce the behavior and I'm reviewing the export logic to figure out the culprit. I'll make sure to update you once I know more.

**Comment by pokornyd** [comment]
Some takeaways from my investigation so far -- there package's configuration (tsconfig, package.json) seems to be in a somewhat invalid state. Most importantly, the subpath exports are not resolving at all and, subsequently, neither does the path to the installed module.

I tried modifying the `exports` and explicitly provide type definition for each subpath but to no avail. Interestingly, updating TypeScript to the latest version yields a new set of errors, where `tsc` complains about `module` and `moduleResolution` not being both set to `nodenext`, despite that not being the case:

![image](https://github.com/kontent-ai/rich-text-resolver-js/assets/52500882/0c1210fa-597f-4577-81c7-44a460849b4c)

I'll try to get to the bottom of this, but will probably release a quick hotfix in the meantime, while minimizing the effect on public API. I'll also revert the `exports` in package.json to their original state, just in case they work in some scenarios, though I haven't so far managed to make this work in any environment.

Thank you very much for your patience so far.
